apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: go-potivqlf 
  janus-idp.io/tekton: go-potivqlf
  backstage.io/kubernetes-id: go-potivqlf
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: go-potivqlf
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml